name: firebase_database_web
description: The web implementation of firebase_database
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database_web
version: 0.1.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: DatabaseWeb
        fileName: firebase_database_web.dart
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.3.0
  http_parser: ^3.1.3
  meta: ^1.1.7
  firebase_core: ^0.5.0
  js: ^0.6.1
  firebase_database_platform_interface:
    git:
      url: https://github.com/gangadharashettypj/flutter_firebase_libs
      ref: master
      path: firebase_database/firebase_database_platform_interface
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^1.0.0
  firebase_core_web: ^0.1.1
  mockito: ^4.1.1
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
